project_id = "otiqpklbednbytyvaoah"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.create-booking-payment]
verify_jwt = true

[functions.create-tournament-payment]
verify_jwt = true

[functions.confirm-booking-payment]
verify_jwt = false

[functions.confirm-tournament-payment]
verify_jwt = false

[functions.send-booking-reminders]
verify_jwt = false

[functions.send-challenge-reminders]
verify_jwt = false

[functions.create-notification]
# Requires authentication - don't set verify_jwt = false

[functions.create-ad-payment]
verify_jwt = true

[functions.confirm-ad-payment]
verify_jwt = false

[functions.cancel-tournament]
verify_jwt = true

[functions.accept-friend-request]
# Requires authentication - don't set verify_jwt = false

[functions.cleanup-friend-requests]
# Requires authentication - don't set verify_jwt = false